-- IO_CODA definition

CREATE TABLE  "IO_CODA" 
   (	"ID_CODA" NUMBER NOT NULL ENABLE, 
	"CODICE_FISCALE" VARCHAR2(16) NOT NULL ENABLE, 
	"DATA_INS" DATE, 
	"DATA_INVIO_PREVISTO" DATE, 
	"INTERVALLO_ORARIO_INVIO" NUMBER(*,0), 
	"TIPO_MESSAGGIO" VARCHAR2(255) NOT NULL ENABLE, 
	"PAYLOAD_MESSAGGIO" VARCHAR2(4000) NOT NULL ENABLE, 
	"DATA_SCADENZA" DATE, 
	"NOTICE_NUMBER" VARCHAR2(20), 
	"NOTE" VARCHAR2(4000), 
	"AMOUNT" NUMBER, 
	"INVALID_AFTER_DUE_DATE" VARCHAR2(10), 
	"DATA_PROMEMORIA_IO" VARCHAR2(19), 
	 CONSTRAINT "ID_CODA_PK1" PRIMARY KEY ("ID_CODA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD"  ENABLE, 
	 CONSTRAINT "TIPO_MSG_FK" FOREIGN KEY ("TIPO_MESSAGGIO")
	  REFERENCES  "IO_CONFIGURAZIONE" ("TIPO_BATCH") ENABLE, 
	 CONSTRAINT "INTERVALLO_INVIO_FK" FOREIGN KEY ("INTERVALLO_ORARIO_INVIO")
	  REFERENCES  "IO_INTERVALLO_INVIO" ("ID_INTERVALLO_INVIO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;

CREATE INDEX  "INDEX_CF" ON  "IO_CODA" ("CODICE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;
  CREATE UNIQUE INDEX  "ID_CODA_PK1" ON  "IO_CODA" ("ID_CODA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;

COMMENT ON COLUMN  IO_CODA.ID_CODA IS 'ID univoco della coda';
COMMENT ON COLUMN  IO_CODA.CODICE_FISCALE IS 'CF del cittadino';
COMMENT ON COLUMN  IO_CODA.DATA_INS IS 'Data inserimento in tabella';
COMMENT ON COLUMN  IO_CODA.DATA_INVIO_PREVISTO IS 'Data invio previsto';
COMMENT ON COLUMN  IO_CODA.INTERVALLO_ORARIO_INVIO IS 'Intervallo orario previsto';
COMMENT ON COLUMN  IO_CODA.TIPO_MESSAGGIO IS 'Servizio specifico invocato (valori ammessi su IO_CONFIGURAZIONE)';
COMMENT ON COLUMN  IO_CODA.PAYLOAD_MESSAGGIO IS 'Corpo del messaggio AppIO';
COMMENT ON COLUMN  IO_CODA.DATA_SCADENZA IS 'Data entro cui inviare il messaggio';
COMMENT ON COLUMN  IO_CODA.NOTICE_NUMBER IS 'IUV del pagamento PagoPA (se disponibile)';
COMMENT ON COLUMN  IO_CODA.NOTE IS 'Note aggiuntive';
COMMENT ON COLUMN  IO_CODA.AMOUNT IS 'Importo del pagamento AppIO se presente';
COMMENT ON COLUMN  IO_CODA.INVALID_AFTER_DUE_DATE IS 'Boolean opzionale per il pagamento su  AppIO';
COMMENT ON COLUMN  IO_CODA.DATA_PROMEMORIA_IO IS 'Data in formato ISO 8601 per creare un promemoria AppIO. Es: 2022-01-30T10:11:12';