--  IO_CONFIGURAZIONE definition

CREATE TABLE  "IO_CONFIGURAZIONE" 
   (	"TIPO_BATCH" VARCHAR2(255) NOT NULL ENABLE, 
	"TOKEN" VARCHAR2(50), 
	"PAYLOAD_TYPE" VARCHAR2(10), 
	"SUBJECT" VARCHAR2(120), 
	"TIME_TO_LIVE" NUMBER(6,0), 
	"RIPETIBILE" VARCHAR2(100) DEFAULT 'MAI' NOT NULL ENABLE, 
	"MESSAGGIO_BASE" VARCHAR2(4000), 
	"NOTE" VARCHAR2(1000), 
	"PAYLOAD_MEX" VARCHAR2(4000), 
	"ID_STATO_REC" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"TIPO_DESC_ESTESA" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_IO_CONF" PRIMARY KEY ("TIPO_BATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;

CREATE UNIQUE INDEX  "PK_IO_CONF" ON  "IO_CONFIGURAZIONE" ("TIPO_BATCH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;

COMMENT ON COLUMN  IO_CONFIGURAZIONE.TIPO_BATCH IS 'Servizio specifico invocato';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.TOKEN IS 'Chiave primaria di AppIO';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.PAYLOAD_TYPE IS 'Indica se STATICO o DINAMICO (ad uso batch)';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.SUBJECT IS 'Subject del messaggio per AppIO';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.TIME_TO_LIVE IS 'TTL per AppIO';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.RIPETIBILE IS 'Indica se ripetere o meno l''invio in caso di errore (ad uso batch)';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.MESSAGGIO_BASE IS 'Messaggio di base (pre sostituzioni) per il markdown di AppIO';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.NOTE IS 'Note aggiuntive';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.PAYLOAD_MEX IS 'Vecchia colonna per compatibilita con prod';
COMMENT ON COLUMN  IO_CONFIGURAZIONE.TIPO_DESC_ESTESA IS 'Descrizione estesa del servizio per il cruscotto Elastic';