--  IO_ESITI definition

CREATE TABLE  "IO_ESITI" 
   (	"ID_ESITI" NUMBER NOT NULL ENABLE, 
	"CODICE_FISCALE" VARCHAR2(20), 
	"TIPO_INVIO" VARCHAR2(255) NOT NULL ENABLE, 
	"DATA_INIZIO" TIMESTAMP (6), 
	"DATA_FINE" TIMESTAMP (6), 
	"RESPONSE_CODE" NUMBER, 
	"RESPONSE_DESC" VARCHAR2(1000), 
	"MESSAGE_ID" VARCHAR2(255), 
	"NOTE" VARCHAR2(2000), 
	"COD_INVIO" VARCHAR2(255), 
	"ID_CODA" VARCHAR2(32), 
	"REQUEST" VARCHAR2(4000), 
	"RESPONSE" VARCHAR2(4000), 
	"IS_PAYMENT" VARCHAR2(20), 
	"NOTICE_NUMBER" VARCHAR2(20), 
	"INVIO_TENTATO" VARCHAR2(20), 
	"DATA_INVIO" DATE, 
	"ID_CODA_OLD" NUMBER, 
	"TIPO_BATCH" VARCHAR2(255), 
	"TIPO_DESC_ESTESA" VARCHAR2(100), 
	 CONSTRAINT "IO_ESITI_PK" PRIMARY KEY ("ID_ESITI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;

CREATE UNIQUE INDEX  "IO_ESITI_PK" ON  "IO_ESITI" ("ID_ESITI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;
  CREATE INDEX  "IDX_ESITI_TIPO_INVIO" ON  "IO_ESITI" ("TIPO_INVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;
  CREATE INDEX  "IDX_ESITI_CF" ON  "IO_ESITI" ("CODICE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;
  CREATE INDEX  "IDX_ESITI_ID_CODA" ON  "IO_ESITI" ("ID_CODA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_LD" ;

COMMENT ON COLUMN  IO_ESITI.ID_ESITI IS 'ID univoco su IO_ESITI';
COMMENT ON COLUMN  IO_ESITI.CODICE_FISCALE IS 'CF del cittadino';
COMMENT ON COLUMN  IO_ESITI.TIPO_INVIO IS 'Servizio specifico invocato';
COMMENT ON COLUMN  IO_ESITI.DATA_INIZIO IS 'Timestamp di inizio invio';
COMMENT ON COLUMN  IO_ESITI.DATA_FINE IS 'Timestamp di fine invio';
COMMENT ON COLUMN  IO_ESITI.RESPONSE_CODE IS 'HTTP status code';
COMMENT ON COLUMN  IO_ESITI.RESPONSE_DESC IS 'HTTP status description';
COMMENT ON COLUMN  IO_ESITI.MESSAGE_ID IS 'Codice univoco generato da AppIO se inviato';
COMMENT ON COLUMN  IO_ESITI.NOTE IS 'Note aggiuntive';
COMMENT ON COLUMN  IO_ESITI.COD_INVIO IS 'Codice univoco di log generato da WSO2';
COMMENT ON COLUMN  IO_ESITI.ID_CODA IS 'Nuovo ID che identifica elemento nella coda se batch';
COMMENT ON COLUMN  IO_ESITI.REQUEST IS 'Client request';
COMMENT ON COLUMN  IO_ESITI.RESPONSE IS 'Risposta per il client';
COMMENT ON COLUMN  IO_ESITI.IS_PAYMENT IS 'Flag pagamento PagoPA';
COMMENT ON COLUMN  IO_ESITI.NOTICE_NUMBER IS 'Numero avviso PagoPA';
COMMENT ON COLUMN  IO_ESITI.INVIO_TENTATO IS 'Flag per capire se abbiamo almeno provato a chiamare AppIO';
COMMENT ON COLUMN  IO_ESITI.DATA_INVIO IS 'Per compatibilita con prod';
COMMENT ON COLUMN  IO_ESITI.ID_CODA_OLD IS 'Per compatibilita con prod';
COMMENT ON COLUMN  IO_ESITI.TIPO_BATCH IS 'Per compatibilita con prod';
COMMENT ON COLUMN  IO_ESITI.TIPO_DESC_ESTESA IS 'Descrizione estesa del servizio per il cruscotto Elastic';